(()=>{
chrome.runtime.onMessage.addListener((m,_s,reply)=>{
  if(m?.type==='FIBI_PING'){reply({ok:true});return}
  if(m?.type==='FIBI_SUMMARY'){try{reply({ok:true,data:summary()})}catch(e){reply({ok:false,error:e.message})}return}
  if(m?.type==='FIBI_TRANSACTIONS'){try{reply({ok:true,data:transactions()})}catch(e){reply({ok:false,error:e.message})}return}
  if(m?.type==='FIBI_OWNER'){try{reply({ok:true,data:owner()})}catch(e){reply({ok:false,error:e.message})}return}
  if(m?.type==='FIBI_LOANS'){try{reply({ok:true,data:loans()})}catch(e){reply({ok:false,error:e.message})}return}
});
let reported='';function report(){if(location.hostname==='online.fibi.co.il'&&location.hash&&location.hash!==reported){reported=location.hash;chrome.runtime.sendMessage({type:'FIBI_AUTHENTICATED'}).catch(()=>{})}}report();setInterval(report,1000);
function text(el){return(el?.innerText||el?.textContent||'').replace(/\s+/g,' ').trim()}
function money(v){const s=String(v||'').replace(/[−–]/g,'-'),neg=s.includes('-'),clean=s.replace(/[,₪\s]/g,'').replace(/[^0-9.\-]/g,'');if(!clean||clean==='-')return null;const n=Number(clean.replace(/-/g,''));return Number.isFinite(n)?(neg?-n:n):null}
function afterLabel(label){const all=[...document.querySelectorAll('body *')];const el=all.find(x=>text(x)===label);if(!el)return null;let p=el.parentElement;for(let i=0;i<4&&p;i++,p=p.parentElement){const vals=[...p.querySelectorAll('*')].map(text).filter(x=>/^-?[\d,]+\.\d{2}$/.test(x));if(vals.length)return money(vals[0])}return null}
function account(){const body=text(document.body),m=body.match(/\b(\d{3})-(\d{5,7})\b/);if(!m)throw Error('לא נמצא מספר החשבון בבינלאומי');return{branch:m[1],accountNumber:m[2]}}
function summary(){const a=account(),balance=afterLabel('יתרת עו״ש עדכנית');const body=text(document.body);const loanMatch=body.match(/הלוואות\s*([\d,]+(?:\.\d{2})?)/);const cardMatch=body.match(/סך החיובים הבאים:[\s\S]{0,60}?([\d,]+\.\d{2})/);const suffix=(body.match(/החיוב הבא:[\s\S]{0,80}?\b(\d{4})\b/)||body.match(/\b(\d{4})\b[\s\S]{0,40}?החיוב הבא/))?.[1]||'';return{...a,balance,loansTotal:loanMatch?money(loanMatch[1]):null,upcomingCardCharges:cardMatch?money(cardMatch[1]):null,cards:suffix?[{suffix,name:'כרטיס הבינלאומי',issuer:'הבינלאומי',amount:cardMatch?money(cardMatch[1]):0,transactions:[]}]:[]}}
function transactions(){const frame=document.querySelector('#iframe-old-pages'),doc=frame?.contentDocument;if(!doc)throw Error('דף התנועות של הבינלאומי עדיין לא נטען');const body=text(doc.body);const branch=(body.match(/סניף:\s*(\d+)/)||[])[1],accountNumber=(body.match(/מספר חשבון:\s*(\d+)/)||[])[1];const current=money((body.match(/יתרה עדכנית\s*([\d,.-]+)₪/)||[])[1]);const withdraw=money((body.match(/יתרה למשיכה\s*([\d,.-]+)₪/)||[])[1]);const table=[...doc.querySelectorAll('table')].find(t=>[...t.querySelectorAll('tr')].some(r=>/^\d{2}\/\d{2}\/\d{4}/.test(text(r))));if(!table)throw Error('לא נמצאה טבלת התנועות בבינלאומי');const rows=[...table.querySelectorAll('tr')].map(r=>{const c=[...r.querySelectorAll('td')].map(text);if(c.length<6||!/^\d{2}\/\d{2}\/\d{4}$/.test(c[0]))return null;return{date:c[0],action:c[1],details:'',reference:c[2],credit:money(c[3]),debit:money(c[4]),balance:money(c[5])}}).filter(Boolean);return{branch,accountNumber,balance:current,creditLimit:current!=null&&withdraw!=null?withdraw-current:null,availableCredit:withdraw,transactions:rows}}
function owner(){const result=name=>{const fullName=String(name||'').replace(/\s+/g,' ').trim(),parts=fullName.split(/\s+/).filter(Boolean);return{fullName,firstName:parts.length>1?parts.slice(1).join(' '):parts[0]||''}};const doc=document.querySelector('#iframe-old-pages')?.contentDocument;if(!doc)throw Error('אישור ניהול החשבון עדיין לא נטען');const line=[...doc.querySelectorAll('body *')].map(el=>(el.innerText||el.textContent||'').trim()).find(v=>/^לכבוד\s*:\s*[^\r\n]+/.test(v));if(line){const fullName=(line.match(/^לכבוד\s*:\s*([^\r\n]+)/)||[])[1];if(fullName)return result(fullName)}const tables=[...doc.querySelectorAll('table')];for(const table of tables){const rows=[...table.querySelectorAll('tr')],index=rows.findIndex(r=>/שם לקוח/.test(text(r)));if(index<0)continue;const cells=[...(rows[index+1]?.querySelectorAll('td')||[])].map(text);if(cells[0])return result(cells[0])}throw Error('לא נמצא שם בעל החשבון אחרי לכבוד באישור')}
function loans(){const doc=document.querySelector('#iframe-old-pages')?.contentDocument;if(!doc)throw Error('דף פירוט ההלוואות עדיין לא נטען');const tables=[...doc.querySelectorAll('table')].filter(t=>/שם ההלוואה/.test(text(t))&&/סכום הלוואה מקורי/.test(text(t))&&/סך החוב/.test(text(t))).sort((a,b)=>a.querySelectorAll('tr').length-b.querySelectorAll('tr').length);const table=tables[0];if(!table)return{loans:[],loansTotal:0};
// רק שורות שהטבלה היא האב הקרוב שלהן. querySelectorAll('tr') כלל בעבר גם טבלאות
// פנימיות של פירוט ויצר אותה הלוואה פעמיים.
const rows=[...table.querySelectorAll('tr')].filter(r=>r.closest('table')===table),seen=new Set(),items=[];
for(const r of rows){const cells=[...r.children].filter(el=>el.tagName==='TD'),c=cells.map(text);if(c.length!==9||!c[0]||c[0]==='סה"כ')continue;const item={type:c[0],originalPrincipal:money(c[1]),startDate:c[2],interest:c[3],balance:money(c[4]),endDate:c[5],nextPayment:money(c[6]),nextPaymentDate:c[7]};if(!(item.balance>0&&item.nextPayment>0))continue;const key=[item.type,item.originalPrincipal,item.balance,item.endDate,item.nextPayment,item.nextPaymentDate,item.interest].join('|');if(seen.has(key))continue;seen.add(key);
// לוח הסילוקין חושף את מספר התשלום הקרוב (למשל 16). מספר התשלומים שנותרו
// מחושב באופן כולל בין מועד התשלום הקרוב למועד הסופי, והסה"כ הוא ששולמו + נותרו.
const schedule=cells[8]?.querySelector('a[href*="luachSilukin"]'),args=(schedule?.getAttribute('href')?.match(/luachSilukin\(([^)]+)\)/)||[])[1]?.split(',').map(v=>Number(String(v).trim()));if(args?.length===3)item.scheduleArgs=args;
items.push(item)}return{loans:items,loansTotal:items.reduce((sum,x)=>sum+(x.balance||0),0)}}
})();
