(()=>{
const clean=v=>String(v||'').replace(/[\u200e\u200f]/g,'').replace(/\s+/g,' ').trim();
const amount=v=>{const m=clean(v).replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):0};
const monthNames=['ינואר','פברואר','מרץ','אפריל','מאי','יוני','יולי','אוגוסט','ספטמבר','אוקטובר','נובמבר','דצמבר'];
const normalizeMonth=v=>String(v||'').replace(/\D/g,'');
function selectedMonth(){const buttons=[...document.querySelectorAll('button')],selected=buttons.find(b=>b.getAttribute('aria-selected')==='true');if(!selected)return'';const text=clean(selected.innerText),name=monthNames.find(x=>text.includes(x)),year=text.match(/(?:^|\s)(\d{2,4})(?:\s|$)/)?.[1];if(!name||!year)return'';return`${String(monthNames.indexOf(name)+1).padStart(2,'0')}${year.length===2?'20'+year:year}`}
function selectMonth(wanted){const target=normalizeMonth(wanted);if(!/^\d{6}$/.test(target))return{ok:false,error:'חודש לא תקין'};const buttons=[...document.querySelectorAll('button')],months=buttons.filter(b=>monthNames.includes(clean(b.innerText).replace(/\s+\d{2,4}$/,''))),selectedIndex=months.findIndex(b=>b.getAttribute('aria-selected')==='true'),current=selectedMonth();if(selectedIndex<0||!current)return{ok:false,error:'החודש הפעיל לא זוהה'};if(current===target)return{ok:true,month:current};const currentDate=new Date(Number(current.slice(2)),Number(current.slice(0,2))-1,1),targetDate=new Date(Number(target.slice(2)),Number(target.slice(0,2))-1,1),offset=(targetDate.getFullYear()-currentDate.getFullYear())*12+targetDate.getMonth()-currentDate.getMonth(),button=months[selectedIndex+offset];if(!button)return{ok:false,error:`החודש ${target} אינו זמין בבורר`};button.click();return{ok:true,clicked:true,from:current,target}}
function cards(){const out=[];for(const option of document.querySelectorAll('button')){const text=clean(option.getAttribute('aria-label')||option.innerText),suffix=text.match(/\|\s*(\d{4})(?!\d)/)?.[1]||text.match(/מסתיים ב\s*(\d{4})/)?.[1];if(!suffix||!/(?:נותר לניצול|חיוב קרוב|מסגרת)/.test(text))continue;const name=(text.match(/כרטיס\s+(.+?)\s*\|/)||text.match(/^[^|]*?\s+([^|]+?)\s*\|/))?.[1]||'ישראכרט';const chargeText=text.match(/\|\s*\d{4}.*?₪\s*([\d,]+)\s*\.\s*(\d{2})/),charge=chargeText?Number(`${chargeText[1].replace(/,/g,'')}.${chargeText[2]}`):0;const limit=amount(text.match(/(?:מתוך|מסגרת:)\s*₪?\s*[\d,]+(?:\.\d+)?/)?.[0]);const date=text.match(/(?:לחיוב (?:בתאריך|ב-)|ב-)(\d{1,2}[\./]\d{1,2})/)?.[1]||'';out.push({suffix,name:clean(name),issuer:'ישראכרט',amount:charge,creditLimit:limit,chargeDate:date,cancelled:/מבוטל/.test(text),transactions:[]})}return[...new Map(out.map(x=>[x.suffix,x])).values()]}
function transactions(){const out=[],seen=new Set();for(const b of document.querySelectorAll('button')){const raw=clean(b.getAttribute('aria-label')||b.getAttribute('title')||b.innerText),date=raw.match(/(?:בתאריך\s+)?(\d{2}\.\d{2}\.\d{2,4})/)?.[1];if(!date)continue;const sumText=raw.match(/(?:בסכום\s+)?₪\s*([\d,]+(?:\.\d{1,2})?)/),sum=sumText?amount(sumText[1]):0;if(!sumText)continue;let merchant=raw.replace(/^עסקה\s+\d+\s+מתוך\s+\d+\s+/,'').split(/\s+(?:בסכום\s+)?₪/)[0];if(!merchant){const lines=String(b.innerText||'').split(/\n+/).map(clean).filter(Boolean);merchant=lines.find(x=>!/^₪|^\d{2}\.\d{2}\./.test(x))||''}merchant=clean(merchant);if(!merchant||/^(?:הדפסה|הורדה|חזרה)/.test(merchant))continue;const key=`${date}|${merchant}|${sum}`;if(seen.has(key))continue;seen.add(key);out.push({date,merchant,amount:sum,payments:/הוראת קבע/.test(raw)?'הוראת קבע':''})}return out}
function cycleTotal(){const text=clean(document.querySelector('main')?.innerText),m=text.match(/סה["״']?כ לחיוב החודש בכרטיס בש["״']?ח\s*₪?\s*([\d,]+(?:\.\d{1,2})?)/);return m?amount(m[1]):outTotal(transactions())}
function outTotal(rows){return Math.round(rows.reduce((s,x)=>s+(Number(x.amount)||0),0)*100)/100}
function transactionFingerprint(){const rows=transactions();return JSON.stringify({total:cycleTotal(),rows:rows.map(x=>[x.date,x.merchant,x.amount,x.payments])})}
chrome.runtime.onMessage.addListener((m,s,reply)=>{if(m?.type==='ISRACARD_PING'||m?.type==='ISRACARD_PING_V3'){reply({ok:true,adapterVersion:3});return}if(m?.type==='ISRACARD_SELECT_MONTH'||m?.type==='ISRACARD_SELECT_MONTH_V3'){reply(selectMonth(m.month));return}if(m?.type==='ISRACARD_READY'||m?.type==='ISRACARD_READY_V3'){const text=clean(document.querySelector('main')?.innerText),url=new URL(location.href),suffix=url.searchParams.get('cardSuffix')||'';reply({ok:true,adapterVersion:3,ready:/עסקאות למועד חיוב|סה["״']?כ לחיוב החודש/.test(text),suffix,month:selectedMonth(),fingerprint:transactionFingerprint()});return}if(m?.type==='ISRACARD_SUMMARY'){const value=cards();reply({ok:true,cards:value,owner:clean(document.querySelector('main')?.innerText.match(/(?:ערב|בוקר|צהריים) טוב\s+([^,\n]+)/)?.[1]||'')});return}if(m?.type==='ISRACARD_TRANSACTIONS'||m?.type==='ISRACARD_TRANSACTIONS_V3'){const rows=transactions();reply({ok:true,adapterVersion:3,transactions:rows,total:cycleTotal(),month:selectedMonth(),fingerprint:transactionFingerprint()});return}});

// דיווח התחברות: משתמש באותו סימן שהמתאם כבר סומך עליו לזיהוי דף טעון ומחובר.
let isracardReported=false;
function reportIsracard(){if(isracardReported)return;
const t=(document.body?.innerText||'');
// דורש סימן של דף הסטטוס עם רשימת הכרטיסים, ולא של דף כרטיס בודד
if(!/נותר לניצול|מסגרת/.test(t))return;
if(/^\/transactions/.test(location.pathname))return;
isracardReported=true;chrome.runtime.sendMessage({type:'ISRACARD_AUTHENTICATED'}).catch(()=>{})}
setInterval(reportIsracard,1000);reportIsracard();
})();
