(()=>{
const clean=v=>String(v||'').replace(/[\u200e\u200f\u202a-\u202e]/g,'').replace(/\s+/g,' ').trim(),wait=ms=>new Promise(r=>setTimeout(r,ms));
const money=v=>{const m=clean(v).replace(/[−–]/g,'-').match(/-?[\d,]+(?:\.\d{1,2})?/);return m?Number(m[0].replace(/,/g,'')):null};
function authenticated(){return /(^|\.)max\.co\.il$/.test(location.hostname)&&/היי\s+[^\n(]+\s*\(:|התנתקו/.test(document.body?.innerText||'')}
function report(){if(authenticated())chrome.runtime.sendMessage({type:'MAX_AUTHENTICATED'}).catch(()=>{})}report();setInterval(report,5000);
function monthKey(){const t=clean(document.querySelector('.combo-text.dates')?.textContent),names={ינואר:'01',פברואר:'02',מרץ:'03',אפריל:'04',מאי:'05',יוני:'06',יולי:'07',אוגוסט:'08',ספטמבר:'09',אוקטובר:'10',נובמבר:'11',דצמבר:'12'},m=t.match(/(ינואר|פברואר|מרץ|אפריל|מאי|יוני|יולי|אוגוסט|ספטמבר|אוקטובר|נובמבר|דצמבר)\s+(\d{4})/);return m?`${names[m[1]]}.${m[2]}`:''}
function rows(){return[...document.querySelectorAll('.row.body')].map(r=>{const date=clean(r.querySelector('.cell.date')?.textContent),merchant=clean(r.querySelector('.cell.name')?.textContent),category=clean(r.querySelector('.cell.category')?.textContent),suffix=clean(r.querySelector('.cell.card-number')?.textContent).replace(/\D/g,'').slice(-4),type=clean(r.querySelector('.cell.type')?.textContent),sumText=clean(r.querySelector('.cell.sum')?.textContent),ils=[...sumText.matchAll(/₪\s*(-?[\d,]+(?:\.\d{1,2})?)/g)],amount=ils.length?Number(ils.at(-1)[1].replace(/,/g,'')):money(sumText);return/^\d{2}\.\d{2}\.\d{2,4}$/.test(date)&&merchant&&Number.isFinite(amount)?{date,merchant,category,suffix,type,amount}:null}).filter(Boolean)}
function read(){const transactions=rows(),body=clean(document.querySelector('main')?.innerText),cards={};for(const t of transactions)(cards[t.suffix]||(cards[t.suffix]=[])).push(t);const total=money((body.match(/סה"כ\s*₪?\s*([\d,.-]+)/)||[])[1]);return{ok:true,month:monthKey(),total,transactions,cards,fingerprint:`${monthKey()}|${transactions.length}|${transactions.slice(0,3).map(x=>`${x.date}:${x.merchant}:${x.amount}`).join('|')}`}}
async function selectMonth(label){const open=document.querySelector('.combo.dates .open-menu');if(!open)return{ok:false,error:'בורר החודשים של MAX לא נמצא'};open.click();await wait(250);const item=[...document.querySelectorAll('li.month,[role="button"]')].find(e=>clean(e.textContent)===clean(label));if(!item)return{ok:false,error:`החודש ${label} לא נמצא בבורר MAX`};item.click();return{ok:true}}
function monthLabels(){return[...new Set([...document.querySelectorAll('li.month,[role="button"]')].map(e=>clean(e.textContent)).filter(t=>/^(?:\u05d9\u05e0\u05d5\u05d0\u05e8|\u05e4\u05d1\u05e8\u05d5\u05d0\u05e8|\u05de\u05e8\u05e5|\u05d0\u05e4\u05e8\u05d9\u05dc|\u05de\u05d0\u05d9|\u05d9\u05d5\u05e0\u05d9|\u05d9\u05d5\u05dc\u05d9|\u05d0\u05d5\u05d2\u05d5\u05e1\u05d8|\u05e1\u05e4\u05d8\u05de\u05d1\u05e8|\u05d0\u05d5\u05e7\u05d8\u05d5\u05d1\u05e8|\u05e0\u05d5\u05d1\u05de\u05d1\u05e8|\u05d3\u05e6\u05de\u05d1\u05e8)\s+\d{4}$/.test(t)))]}
async function monthList(){let labels=monthLabels();if(labels.length)return{ok:true,labels,opened:false};const open=document.querySelector('.combo.dates .open-menu');if(!open)return{ok:false,error:'בורר החודשים של MAX לא נמצא'};open.click();await wait(350);labels=monthLabels();open.click();await wait(200);return{ok:true,labels,opened:true}}
chrome.runtime.onMessage.addListener((m,s,reply)=>{if(m?.type==='MAX_MONTHS'){monthList().then(reply);return true}if(m?.type==='MAX_PING'){reply({ok:true});return}if(m?.type==='MAX_READ'){reply(read());return}if(m?.type==='MAX_SELECT_MONTH'){selectMonth(m.label).then(reply);return true}});
})();
