(()=>{
// שומר הזרקה עמיד למות הקשר — ראה discount-content.js
if(window.__mizrahiSyncLoaded){try{if(window.__mizrahiSyncLoaded())return}catch(e){}}
// ⚠ ההפניה נתפסת כאן ולא נקראת מחדש בכל בדיקה: קריאה מחדש
// מחזירה את ה-chrome החדש, והגשש מדווח „חי" גם כשההקשר שלו מת. נתפס בבדיקה.
const __rt__mizrahiSyncLoaded=(()=>{try{return chrome.runtime}catch(e){return null}})();
window.__mizrahiSyncLoaded=()=>{try{return !!(__rt__mizrahiSyncLoaded&&__rt__mizrahiSyncLoaded.id)}catch(e){return false}};

const clean=v=>String(v??'').replace(/[\u200e\u200f\u202a-\u202e]/g,'').replace(/\s+/g,' ').trim();
const money=v=>{const m=clean(v).replace(/[−–]/g,'-').match(/-?[\d,]+(?:\.\d{1,2})?/);if(!m)return null;const n=Number(m[0].replace(/,/g,''));return Number.isFinite(n)?n:null};
const docs=()=>{const out=[document];for(const f of document.querySelectorAll('iframe'))try{if(f.contentDocument)out.push(f.contentDocument)}catch{}return out};
const bodyText=()=>docs().map(d=>clean(d.body?.innerText)).join(' ');
let frameCache={transactions:[],loans:[]},publish=()=>{};
function current(){const candidates=[...document.querySelectorAll('button')].map(x=>clean(x.innerText));let hit=candidates.find(t=>/\b\d{3}\s*-\s*\d{5,9}\b/.test(t));if(!hit)hit=bodyText();const m=hit.match(/\b(\d{3})\s*-\s*(\d{5,9})\b/)||hit.match(/\b(\d{5,9})\s*-\s*(\d{3})\b/);if(!m)return null;const reversed=m[1].length>3,branch=reversed?m[2]:m[1],accountNumber=reversed?m[1]:m[2];const owner=(candidates.find(t=>t.includes(`${branch}-${accountNumber}`))||hit).replace(new RegExp(`${branch}\\s*-\\s*${accountNumber}|${accountNumber}\\s*-\\s*${branch}`),'').trim();return{branch,accountNumber,owner:owner||'חשבון מזרחי',key:`${branch}-${accountNumber}`}}
function discover(){const found=new Map(),rx=/\b(\d{3})\s*-\s*(\d{5,9})\b/g;for(const d of docs())for(const el of d.querySelectorAll('button,[role="button"],li')){const t=clean(el.innerText);let m;while((m=rx.exec(t)))found.set(`${m[1]}-${m[2]}`,{branch:m[1],accountNumber:m[2],owner:t.replace(m[0],'').trim()||'חשבון מזרחי',nickname:t.replace(m[0],'').trim()||'חשבון מזרחי',key:`${m[1]}-${m[2]}`})}const c=current();if(c&&!found.has(c.key))found.set(c.key,{...c,nickname:c.owner});return[...found.values()]}
function summary(){const c=current();if(!c)throw Error('מספר החשבון הפעיל לא זוהה');const t=bodyText(),balance=money((t.match(/יתרת עו["״']ש\s*([\d,.-]+)\s*₪/)||[])[1]),creditLimit=money((t.match(/מסגרת אשראי בחשבון\s*([\d,.-]+)\s*₪/)||[])[1]);return{...c,nickname:c.owner,balance,creditLimit,availableCredit:balance==null||creditLimit==null?null:balance+creditLimit}}
function transactions(){const rows=[];for(const d of docs())for(const row of d.querySelectorAll('[role="row"],tr')){const cells=[...row.querySelectorAll('[role="gridcell"],td')].map(x=>({text:clean(x.innerText),label:clean(x.getAttribute('aria-label'))})),dateCell=cells.find(c=>/^\d{1,2}\/\d{1,2}\/\d{2,4}$/.test(c.text));if(!dateCell)continue;const actionCell=cells.find(c=>/סוג תנועה/.test(c.label)),amountCell=cells.find(c=>/זכות\s*\/\s*חובה/.test(c.label)),balanceCell=cells.find(c=>/יתרה/.test(c.label));const amount=money(amountCell?.text),balance=money(balanceCell?.text);rows.push({date:dateCell.text,action:actionCell?.text||'',details:'',debit:amount!=null&&amount<0?Math.abs(amount):null,credit:amount!=null&&amount>=0?amount:null,balance})}return rows}
function setThreeMonths(){for(const d of docs()){const button=[...d.querySelectorAll('button,[role="button"]')].find(x=>/3\s*חודשים\s*אחרונים/.test(clean(x.innerText)));if(button){button.click();return true}}return false}
function loans(){const out=[];for(const d of docs())for(const row of d.querySelectorAll('[role="row"],tr,.loan,.loan-details')){const t=clean(row.innerText);if(!/הלווא|יתרה|קרן|ריבית/.test(t))continue;const nums=(t.match(/-?[\d,]+(?:\.\d{1,2})?/g)||[]).map(x=>Number(x.replace(/,/g,''))).filter(Number.isFinite);const dates=t.match(/\d{1,2}\/\d{1,2}\/\d{2,4}/g)||[];const rate=(t.match(/(?:ריבית[^\d]{0,20})([\d.]+\s*%|P\s*[+-]\s*[\d.]+%?)/i)||[])[1]||'';if(!nums.length)continue;out.push({type:(t.match(/הלווא[^:]{0,40}/)||[])[0]||'הלוואה במזרחי',balance:nums[0],originalPrincipal:null,nextPayment:nums.length>1?nums.at(-1):null,nextPaymentDate:dates[0]||'',endDate:dates.at(-1)||'',interest:rate})}return out.slice(0,30)}
if(window===top){window.addEventListener('message',e=>{if(e.source===window||!e.data?.__mizrahiFrame)return;const d=e.data;if(Array.isArray(d.transactions)&&d.transactions.length)frameCache.transactions=d.transactions;if(Array.isArray(d.loans)&&d.loans.length)frameCache.loans=d.loans})}else{publish=()=>{try{const data={__mizrahiFrame:true,transactions:transactions(),loans:loans()};parent.postMessage(data,'*');chrome.runtime.sendMessage({type:'MIZRAHI_FRAME_REPORT',transactions:data.transactions,loans:data.loans}).catch(()=>{})}catch{}};publish();setTimeout(publish,900);setTimeout(publish,2200)}
chrome.runtime.onMessage.addListener((m,s,reply)=>{try{if(m?.type==='PING')return reply({ok:true});if(m?.type==='MIZRAHI_SET_RANGE'){const clicked=setThreeMonths();if(clicked&&window!==top){setTimeout(publish,1200);setTimeout(publish,3000)}return reply({ok:true,clicked})}if(m?.type==='MIZRAHI_DISCOVER')return reply({ok:true,accounts:discover()});if(m?.type==='MIZRAHI_READ'){const a=summary(),rows=transactions();return reply({ok:true,account:{...a,transactions:rows.length?rows:frameCache.transactions}})}if(m?.type==='MIZRAHI_LOANS'){const rows=loans();return reply({ok:true,loans:rows.length?rows:frameCache.loans})}}catch(e){reply({ok:false,error:e.message})}});
try{if(window===top&&location.pathname.startsWith('/OnlineApp/'))chrome.runtime.sendMessage({type:'MIZRAHI_AUTHENTICATED'}).catch(()=>{})}catch{}
})();
