(()=>{
  if(globalThis.__banksYahavLoaded)return;globalThis.__banksYahavLoaded=true;
  const clean=v=>String(v??'').replace(/[\u200e\u200f\u202a-\u202e]/g,'').replace(/\s+/g,' ').trim();
  const num=v=>{const m=clean(v).replace(/[−–]/g,'-').match(/-?[\d,]+(?:\.\d{1,2})?/);if(!m)return null;const n=Number(m[0].replace(/,/g,''));return Number.isFinite(n)?n:null};
  const body=()=>clean(document.body?.innerText||'');
  const account=()=>{const m=body().match(/(?:החשבונות שלי\s*)?(\d{2,4})\s*[-–]\s*(\d{3,12})/);return m?{branch:m[1],accountNumber:m[2]}:null};
  const owner=()=>{const m=body().match(/שלום,\s*([^\n]{1,40})/);return clean(m?.[1]||'').split(' ')[0]||''};
  const transactions=()=>{const out=[];for(const row of document.querySelectorAll('[role="row"]')){const cells=[...row.querySelectorAll('[role="gridcell"]')].map(x=>clean(x.innerText));if(cells.length<5||!/^\d{2}\/\d{2}\/\d{4}$/.test(cells[0]))continue;const hasReference=cells.length>=6;out.push({date:cells[0],action:cells[hasReference?2:1],details:hasReference?cells[1]:'',debit:num(cells[hasReference?3:2]),credit:num(cells[hasReference?4:3]),balance:num(cells[hasReference?5:4])})}return out};
  const loans=()=>{const out=[];for(const row of document.querySelectorAll('[role="row"]')){const c=[...row.querySelectorAll('[role="gridcell"]')].map(x=>clean(x.innerText));if(c.length<6||!c[0]||num(c[2])==null)continue;out.push({type:c[0],interest:c[1]?`${c[1]}%`:'',balance:num(c[2]),originalPrincipal:num(c[3]),nextPaymentDate:c[4],nextPayment:num(c[5])})}return out};
  const field=(label,nextLabels)=>{const t=body(),i=t.indexOf(label);if(i<0)return'';let s=t.slice(i+label.length);for(const n of nextLabels){const p=s.indexOf(n);if(p>=0)s=s.slice(0,p)}return clean(s)};
  const detail=()=>{const t=body(),match=re=>(t.match(re)||[])[1]||'';return{type:match(/סוג הלוואה\s+(.+?)\s+קרן הלוואה מקורית/),originalPrincipal:num(match(/קרן הלוואה מקורית\s+([\d,.]+)/)),endDate:match(/תאריך סיום ההלוואה\s+(\d{2}\/\d{2}\/\d{4})/),nextPaymentDate:match(/תאריך התשלום הבא\s+(\d{2}\/\d{2}\/\d{4})/),startDate:match(/תאריך תחילת ההלוואה\s+(\d{2}\/\d{2}\/\d{4})/),balance:num(match(/יתרה משוערת\s+([\d,.]+)/)),nextPayment:num(match(/סכום התשלום הבא\s+([\d,.]+)/)),interest:match(/ריבית נוכחית \(%\)\s+([\d.]+)/)}};
  const summary=()=>{let balance=null,creditLimit=null,loanBalance=null;for(const row of document.querySelectorAll('table [role="row"],table tr')){const c=[...row.querySelectorAll('[role="gridcell"],td')].map(x=>clean(x.innerText));if(c[0]==='חשבון עו״ש'&&balance==null)balance=num(c[1]);if(c[0]==='הלוואות'&&loanBalance==null)loanBalance=num(c[1])}const m=body().match(/מסגרת אשראי\s+([\d,.]+)/);if(m)creditLimit=num(m[1]);return{balance,creditLimit,loanBalance}};
  const setThreeMonths=async()=>{const input=[...document.querySelectorAll('input.date-picker-input,input[placeholder="dd/MM/y"]')][0];if(!input)return false;const box=input.closest('.date-picker-box')||input.parentElement?.parentElement,group=input.closest('[role="group"],.input-group')||input.parentElement,open=group?.querySelector('a.datepicker-button,[role="button"]');if(!open||!box)return false;open.click();await new Promise(r=>setTimeout(r,220));const dialog=box.querySelector('[role="dialog"]');if(!dialog)return false;for(let i=0;i<3;i++){const prev=dialog.querySelector('.datepicker-month-prev:not(.disabled)');if(!prev)return false;prev.click();await new Promise(r=>setTimeout(r,260))}const targetDay=new Date().getDate(),target=[...dialog.querySelectorAll('[role="gridcell"].selectable')].find(c=>c.dataset.value===String(targetDay)&&c.getAttribute('aria-disabled')!=='true');if(!target)return false;target.click();await new Promise(r=>setTimeout(r,700));return true};
  chrome.runtime.onMessage.addListener((m,s,r)=>{if(m?.type==='YAHAV_READ'){r({ok:true,account:account(),owner:owner(),transactions:transactions(),loans:loans(),detail:detail(),summary:summary(),text:body()});return}if(m?.type==='YAHAV_SET_3_MONTHS'){setThreeMonths().then(ok=>r({ok}));return true}if(m?.type==='PING')r({ok:true})});
  chrome.runtime.sendMessage({type:'YAHAV_AUTHENTICATED'}).catch(()=>{});
})();
